### PR TITLE
now works on windows

### PR DESCRIPTION
**Pull request by ShiboSoftwareDev**
@seveibar I got it working on windows but it broke on my linux laptop. Can you find the problematic parts and make them different for each platform. This is a complicated repo, I'd probably be able to fix it but it would take me a lot of time.

### CODE REVIEW

**Comment by ShiboSoftwareDev** [comment]
Or I can tell you why I made those changes and we try to create a fix that works for both platforms, I can join you in a call and you code it live

**Comment by seveibar** [comment]
Yes i can take a look at this and make sure it works on linux!

**Comment by ShiboSoftwareDev** [comment]
no checks are running @seveibar

**Comment by seveibar** [comment]
@ShiboSoftwareDev yes that's strange... might be an issue with out org reaching it's limits. Will look into this now

**Comment by seveibar** [comment]
@ShiboSoftwareDev i just increased our org limit, maybe it'll work with a re-push? Haven't had this issue before so a bit confused

**Comment by ShiboSoftwareDev** [comment]
@seveibar nothing still

**Comment by seveibar** [comment]
Yea this is weird… im going to try a couple quick things

**Pull request closed without merging**
